add_newline = false
format = """\
$time\
$nix_shell\
$os\
$directory\
$container\
${custom.jj}\
$line_break\
$cmd_duration\
$status\
$character\
"""

[character]
success_symbol = "[;](bold green)"

[cmd_duration]
disabled = false
min_time = 5000

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = " ‚ñ° "
truncate_to_repo = false
truncation_length = 100

[git_branch]
symbol = ""

[hostname]
format = "<[$hostname]($style)>"
ssh_only = true
style = "bold dimmed white"
trim_at = "-"

[line_break]
disabled = false

[memory_usage]
disabled = false
format = "[$symbol$ram]($style) "
style = "bold dimmed white"
symbol = "üêè"
threshold = 75

[nix_shell]
disabled = false
format = "[$symbol$name]($style) "
symbol = "‚Äª "

[status]
disabled = false
format = "[$symbol](fg:red)"
map_symbol = true
not_executable_symbol = "Can't Execute"
not_found_symbol = "Not Found"
recognize_signal_code = true
success_symbol = ""
symbol = "√ó"

[time]
disabled = false
format = "[\\[$time\\]](dimmed) "

[custom.jj]
command = "jj-starship --ancestor-bookmark-depth 20"
when = "jj-starship detect"
